version: '3.2'
services:
  packagetracker:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/trackerdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - WEBSOCKET_RELAY_PORT=61614
      - SPRING_RABBITMQ_HOST=
      - SPRING_RABBITMQ_ADDRESSES=localhost
    depends_on:
      - db
      - rabbitmq
  db:
    image: "postgres"
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_DB=trackerdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - package-data:/var/lib/postgresql/data
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
      - 5673:5672
      - 15673:15672
      - 61614:61613
    volumes:
      - ./enabled_plugin:/etc/rabbitmq/enabled_plugins
volumes:
  package-data: { }