version: '3.2'
services:
  db:
    image: "postgres"
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_DB=trackerdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - package-data:/var/lib/postgresql/data

  packagetracker:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db/trackerdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db
volumes:
  package-data: { }